### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '<root-path>/dist\Tampermonkey\sync'

### ISSUE THREAD

**Issue by MichaelToLearn** [xcr1234/tampermonkey-typescript#1]
命令：
```
npm run sync
```

输出：

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> tempermonkey-typescript@1.0.0 sync
> webpack --watch --sync yes

Error: ENOENT: no such file or directory, scandir 'C:\Users\sheng\Desktop\code\js\github\private\zhihu-reader-tampermonkey\dist\Tampermonkey\sync'
    at Object.readdirSync (node:fs:1405:3)
    at findUuid (C:\Users\sheng\Desktop\code\js\github\private\zhihu-reader-tampermonkey\sync.js:30:22)     
    at module.exports (C:\Users\sheng\Desktop\code\js\github\private\zhihu-reader-tampermonkey\sync.js:50:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at module.exports (C:\Users\sheng\Desktop\code\js\github\private\zhihu-reader-tampermonkey\webpack.config.js:29:18)

**Comment by xcr1234** [comment]
最新版本已修复
